# Generated by Django 5.1.1 on 2024-09-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bounce_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribe_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
