# Generated by Django 5.1.1 on 2024-09-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bounce_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='click_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='commission_earned',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='open_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='total_sent_emails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='unsubscribe_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
