# Generated by Django 5.1.1 on 2024-09-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_bounce_rate_company_click_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='interested_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='meetings_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='total_replies',
            field=models.IntegerField(default=0),
        ),
    ]
