# Generated by Django 5.1.1 on 2024-09-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('categories', models.JSONField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('has_website', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_list', to='campaigns.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
