# Generated by Django 5.1.1 on 2024-09-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
