# Generated by Django 5.1.1 on 2024-09-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('meeting', 'Meeting Booked'), ('converted', 'Converted'), ('disqualified', 'Disqualified')], default='new', max_length=50),
        ),
    ]
