# Generated by Django 5.1.1 on 2024-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('converted', 'Converted'), ('disqualified', 'Disqualified')], default='new', max_length=50),
        ),
    ]
